# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chaos Reins
email: carr.donald@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Qt/Linux consultancy company based in San Francisco
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sirspudd.github.io/web" # the base hostname & protocol for your site
twitter_username: sirspudd
github_username:  sirspudd

# Build settings
markdown: kramdown
